#!/usr/bin/env python3
"""Generate knowledge-base metadata CSV for TCM Inquiry Agent."""

import csv
from pathlib import Path

ROWS = [
    {
        "file_id": "TCM-001",
        "title": "八纲辨证完整资料",
        "domain": "TCM",
        "sub_domain": "八纲辨证",
        "doc_type": "course_note",
        "language": "zh-CN",
        "permission_level": "public",
        "tags": "八纲,表里,寒热,虚实,阴阳",
        "summary": "八纲辨证理论基础与临床案例蒸馏笔记",
        "owner": "知识库管理员",
        "status": "active",
        "source_course": "八纲辨证",
        "hours": "2.7",
        "lessons": "33",
        "medical_boundary": "仅供学习，禁止作为个人医疗建议",
    },
    {
        "file_id": "TCM-002",
        "title": "黄帝内经完整资料",
        "domain": "TCM",
        "sub_domain": "黄帝内经",
        "doc_type": "course_note",
        "language": "zh-CN",
        "permission_level": "public",
        "tags": "内经,阴阳五行,脏腑,脉色,天人合一",
        "summary": "《黄帝内经》精讲：生命哲学与诊断心法",
        "owner": "知识库管理员",
        "status": "active",
        "source_course": "黄帝内经",
        "hours": "38.2",
        "lessons": "19",
        "medical_boundary": "仅供学习，禁止作为个人医疗建议",
    },
    {
        "file_id": "TCM-003",
        "title": "伤寒论完整资料",
        "domain": "TCM",
        "sub_domain": "伤寒论",
        "doc_type": "course_note",
        "language": "zh-CN",
        "permission_level": "restricted",
        "tags": "伤寒论,六经辨证,方证,禁忌,经方",
        "summary": "《伤寒论》六经辨证与核心方证表",
        "owner": "知识库管理员",
        "status": "active",
        "source_course": "伤寒论",
        "hours": "28.6",
        "lessons": "15",
        "medical_boundary": "仅供学习；含峻剂高风险内容",
    },
    {
        "file_id": "TCM-004",
        "title": "金匮要略完整资料",
        "domain": "TCM",
        "sub_domain": "金匮要略",
        "doc_type": "course_note",
        "language": "zh-CN",
        "permission_level": "restricted",
        "tags": "金匮,杂病,水饮,妇科,阴实",
        "summary": "《金匮要略》脉证并治与阴实重症理论",
        "owner": "知识库管理员",
        "status": "active",
        "source_course": "金匮要略",
        "hours": "38.3",
        "lessons": "21",
        "medical_boundary": "仅供学习；含高风险案例",
    },
    {
        "file_id": "TCM-005",
        "title": "临床案例完整资料",
        "domain": "TCM",
        "sub_domain": "临床案例",
        "doc_type": "case",
        "language": "zh-CN",
        "permission_level": "restricted",
        "tags": "临床案例,肿瘤,心脏,肝病,肾衰",
        "summary": "临床案例辨证路径（仅理论索引）",
        "owner": "知识库管理员",
        "status": "active",
        "source_course": "临床案例",
        "hours": "7.1",
        "lessons": "48",
        "medical_boundary": "仅供学习；含方药线索",
    },
    {
        "file_id": "TCM-006",
        "title": "神农本草完整资料",
        "domain": "TCM",
        "sub_domain": "神农本草",
        "doc_type": "course_note",
        "language": "zh-CN",
        "permission_level": "restricted",
        "tags": "本草,药性,五味,炮制,峻药",
        "summary": "《神农本草经》药性与配伍原则",
        "owner": "知识库管理员",
        "status": "active",
        "source_course": "神农本草",
        "hours": "29.6",
        "lessons": "16",
        "medical_boundary": "仅供学习；含峻药高风险内容",
    },
    {
        "file_id": "TCM-007",
        "title": "针灸完整资料",
        "domain": "TCM",
        "sub_domain": "针灸",
        "doc_type": "course_note",
        "language": "zh-CN",
        "permission_level": "restricted",
        "tags": "针灸,十二经,奇经八脉,针法",
        "summary": "针灸经络穴位与临床理论索引",
        "owner": "知识库管理员",
        "status": "active",
        "source_course": "针灸",
        "hours": "39.1",
        "lessons": "44",
        "medical_boundary": "仅供学习；含操作索引禁止照做",
    },
    {
        "file_id": "TCM-008",
        "title": "易筋经完整资料",
        "domain": "TCM",
        "sub_domain": "易筋经",
        "doc_type": "course_note",
        "language": "zh-CN",
        "permission_level": "public",
        "tags": "易筋经,五脏逼毒,文式,武式",
        "summary": "易筋经与五脏逼毒法术语索引",
        "owner": "知识库管理员",
        "status": "active",
        "source_course": "易筋经",
        "hours": "0.4",
        "lessons": "3",
        "medical_boundary": "仅供学习，禁止作为个人训练处方",
    },
    {
        "file_id": "TCM-009",
        "title": "仲景心法完整资料",
        "domain": "TCM",
        "sub_domain": "仲景心法",
        "doc_type": "course_note",
        "language": "zh-CN",
        "permission_level": "restricted",
        "tags": "仲景心法,物理医学,经方心法,中虚为明",
        "summary": "张仲景经方心法与物理医学观",
        "owner": "知识库管理员",
        "status": "active",
        "source_course": "仲景心法",
        "hours": "13.6",
        "lessons": "6",
        "medical_boundary": "仅供学习，禁止作为个人医疗建议",
    },
]


def main() -> None:
    out = Path(__file__).resolve().parent.parent / "assets" / "metadata.csv"
    out.parent.mkdir(parents=True, exist_ok=True)
    fieldnames = list(ROWS[0].keys())
    with out.open("w", encoding="utf-8", newline="") as f:
        w = csv.DictWriter(f, fieldnames=fieldnames)
        w.writeheader()
        w.writerows(ROWS)
    print(f"Wrote {out} ({len(ROWS)} rows)")


if __name__ == "__main__":
    main()
